import type { StorefrontCatalog, StorefrontCategory, StorefrontProduct } from './queries'

export const DEMO_CATALOG: StorefrontCatalog = {
  id: 'demo-catalog-id',
  slug: 'demo',
  name: 'La Tienda Demo 🍔',
  description: 'Prueba el storefront sin necesidad de base de datos',
  currency: 'COP',
  language: 'es',
  orderChannel: 'whatsapp',
  contactPhone: '3001234567',
  contactCountryCode: '+57',
  contactEmail: null,
  themeJson: {} as Record<string, unknown>,
  settingsJson: {} as Record<string, unknown>,
  publishedAt: new Date(),
}

export const DEMO_CATEGORIES: StorefrontCategory[] = [
  { id: 'cat-1', name: 'Hamburguesas', slug: 'hamburguesas', position: 0 },
  { id: 'cat-2', name: 'Bebidas', slug: 'bebidas', position: 1 },
  { id: 'cat-3', name: 'Postres', slug: 'postres', position: 2 },
]

export const DEMO_PRODUCTS: StorefrontProduct[] = [
  {
    id: 'prod-1',
    name: 'Hamburguesa Clásica',
    slug: 'hamburguesa-clasica',
    description: 'Carne 100% res, lechuga, tomate, cebolla caramelizada y salsa especial de la casa.',
    price: 18000,
    compareAt: 22000,
    stock: null,
    imagesJson: [],
    categoryId: 'cat-1',
    active: true,
    position: 0,
  },
  {
    id: 'prod-2',
    name: 'Hamburguesa Doble',
    slug: 'hamburguesa-doble',
    description: 'Doble carne, doble queso, tocino crocante y nuestra salsa secreta.',
    price: 26000,
    compareAt: null,
    stock: 10,
    imagesJson: [],
    categoryId: 'cat-1',
    active: true,
    position: 1,
  },
  {
    id: 'prod-3',
    name: 'Veggie Burger',
    slug: 'veggie-burger',
    description: 'Medallón de garbanzos, aguacate, germinados y aderezo tahini. 100% plant-based.',
    price: 20000,
    compareAt: null,
    stock: 5,
    imagesJson: [],
    categoryId: 'cat-1',
    active: true,
    position: 2,
  },
  {
    id: 'prod-4',
    name: 'Limonada de Coco',
    slug: 'limonada-de-coco',
    description: 'Refrescante limonada con crema de coco, menta y hielo.',
    price: 8000,
    compareAt: null,
    stock: null,
    imagesJson: [],
    categoryId: 'cat-2',
    active: true,
    position: 0,
  },
  {
    id: 'prod-5',
    name: 'Brownie con Helado',
    slug: 'brownie-con-helado',
    description: 'Brownie de chocolate caliente con bola de helado de vainilla y salsa de caramelo.',
    price: 12000,
    compareAt: null,
    stock: 0,
    imagesJson: [],
    categoryId: 'cat-3',
    active: true,
    position: 0,
  },
  {
    id: 'prod-6',
    name: 'Agua Natural',
    slug: 'agua-natural',
    description: 'Botella de agua mineral 500ml.',
    price: 3000,
    compareAt: null,
    stock: null,
    imagesJson: [],
    categoryId: 'cat-2',
    active: true,
    position: 1,
  },
]
